name: Bug Report
description: If something isn't working as expected
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Please use a concise and distinct title for the issue.
  - type: textarea
    attributes:
      label: Steps to reproduce the problem
      description: What were you trying to do?
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    attributes:
      label: Expected behaviour
      description: What should have happened?
    validations:
      required: true
  - type: input
    attributes:
      label: Actual behaviour
      description: What happened? If applicable, add screenshots to help explain your problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Specifications
      description: |
        What version or commit hash of DeBio did you find this bug in?

        If a front-end issue, what browser [e.g. chrome, firefox] and operating systems [e.g. windows, macOS] were you using?
    validations:
      required: true